### ISSUE TITLE
Incorrect CS Checklist

### ISSUE THREAD

**Issue by riyawalia** [theRoughCode/WatsMyMajor#117]
According to the 2017-2018 [checklist](https://cs.uwaterloo.ca/current/programs/require/2017-2018/bcs.html), MATH235 is not required and MATH237 can't be taken as an alternative to MATH239. However, the checklist shows MATH235 and MATH237 as options.

<img width="1225" alt="screen shot 2018-11-12 at 3 12 57 pm" src="https://user-images.githubusercontent.com/20255248/48372768-9fc40100-e68d-11e8-90ac-edc37c378348.png">

1. Go to View Majors
2. Select the Math faculty and BCS major
3. Scroll down to the second row

 - OS: Mojave
 - Browser: Google Chrome

**Comment by theRoughCode** [comment]
Will fix this soon, thanks!

**Comment by theRoughCode** [comment]
This is fixed.  BCS no longer includes the faculty core courses.
