### ISSUE TITLE
[My Courses] Changes are gone after logging back in

### ISSUE THREAD

**Issue by riyawalia** [theRoughCode/WatsMyMajor#137]
Moved a few courses from one term to another. Logged out and logged back in. Changes are not there even after trying 3-4 times. 

 - OS: Windows 10
 - Browser Google Chrome

**Comment by theRoughCode** [comment]
Did you have an empty term (term with no courses)?  I found a bug that might be related to yours.  I just pushed those changes.  Could you check again and see if they're fixed?

**Comment by riyawalia** [comment]
I did have an empty term with no courses. Bug has been fixed, thanks!
