### ISSUE TITLE
Making an account failure (No verification email received)

### ISSUE THREAD

**Issue by goosedose** [theRoughCode/WatsMyMajor#143]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by theRoughCode** [comment]
Hey, sorry for the late response.  What's your username?

**Comment by goosedose** [comment]
Yo, it is all good but I am really excited to use it. my username is anasalarbi605

**Comment by theRoughCode** [comment]
Cool, I sent you an email!
