### ISSUE TITLE
Cannot re-add course to My Courses after removing it

### ISSUE THREAD

**Issue by jacobprudhomme** [theRoughCode/WatsMyMajor#172]
**Bug description**
When deleting a course from My Courses and trying to re-add it again (say, to a different term), all in the same editing session, an error occurs.

**To Reproduce**
1. Go to 'My Courses'
2. Click on 'Edit Board'
3. Drag a course to the delete box on the right.
4. Without exiting the editing state, try re-adding the same course to one of the existing terms.
5. Should get error message "Duplicate courses were removed." at the bottom of the screen, and course will not be re-added.

**Expected behavior**
The course should be re-added without error.

**Environment**
 - Platform: Desktop
 - OS: Windows 10
 - Browser: Firefox 84.0

**Additional context**
When I exit out of the editing state by saving or cancelling my modifications and re-enter again by clicking 'Edit Board', I can re-add the course I deleted with no issues.

**Comment by theRoughCode** [comment]
This is fixed with b19aee0768d1f8925736f66627531807865b7482.
