### ISSUE TITLE
Term Level disappears 

### ISSUE THREAD

**Issue by riyawalia** [theRoughCode/WatsMyMajor#55]
I updated all the term levels last night but this morning they disappeared (reset to 1A). I tried it again this morning and it hasn't disappeared yet.

**Comment by theRoughCode** [comment]
Oh it just happened once (last night)?

**Comment by riyawalia** [comment]
It disappeared again today.

**Comment by theRoughCode** [comment]
@riyawalia Could not replicate.  Did it remain as 1A when you refreshed?

**Comment by theRoughCode** [comment]
#103 might've fixed it.  Closing this issue for now.  If it re-occurs, we can re-open this.
