### ISSUE TITLE
Incorrect information about invalid courses 

### ISSUE THREAD

**Issue by riyawalia** [theRoughCode/WatsMyMajor#56]
Searching for ENGL251A, ENGL251B AND ENGL200A lead to a message that they are invalid courses.  However, I can select them from a drop-down menu.

**Comment by theRoughCode** [comment]
Couldn't reproduce this, might've already been fixed.  Closing.

**Comment by riyawalia** [comment]
Searching for ENGL251A, ENGL251B now show valid course pages. However, ENGL 251 is shown in the drop-down menu in the search bar but the course page is invalid. 
ENGL251A and ENGL251B have been combined to just [ENGL251](https://my.cel.uwaterloo.ca/p/form/courses/search/course/sub/ENGL/cat/251/topic/0) 

![image](https://user-images.githubusercontent.com/20255248/49050170-1b569f80-f1b0-11e8-8f25-5da676599d17.png)

**Comment by theRoughCode** [comment]
Fixed, thanks!
