### ISSUE TITLE
Majors list is clipped

### ISSUE THREAD

**Issue by arora-aman** [theRoughCode/WatsMyMajor#62]
<img width="740" alt="screen shot 2018-08-19 at 11 51 55 am" src="https://user-images.githubusercontent.com/4193035/44306167-b4eb0580-a3a6-11e8-842f-e5eceebc45a5.png">

Fixed itself after refresh

**Comment by theRoughCode** [comment]
Could not replicate.  If this error is still present, feel free to reopen the issue!
