### ISSUE TITLE
Major checklist Problem

### ISSUE THREAD

**Issue by FrancesFerrabee** [theRoughCode/WatsMyMajor#77]
Hey Guys! Really cool app but theres a really big problem with your majors...
The check list does not include courses all math majors need to take: i.e. 135,137,136,cs 115/135, cs 136/116. Because of this it is adding these courses as additional math courses that count towards the major.
Thanks

**Comment by theRoughCode** [comment]
Thanks for the catch @FrancesFerrabee!
