### ISSUE TITLE
Text color in verification email is hard to see

### ISSUE THREAD

**Issue by pdtran3k6** [theRoughCode/WatsMyMajor#78]
**Describe the bug**
The text inside the button of the verification email blends in with the color of the button.

**To Reproduce**
Set up email forwarding from your Waterloo email to your Gmail account.
Sign up with your Waterloo email.
Open the email in your Gmail account.

**Expected behavior**
The text should be white.

**Screenshots**
![image](https://user-images.githubusercontent.com/13684483/46217234-4cbd0700-c2f6-11e8-9b03-6853466e21cf.png)

**Desktop (please complete the following information):**
 - OS: Mac OS X 10.13.6 (High Sierra)
 - Browser: Chrome 69.0.3497.92 (Official Build) (64-bit)

**Comment by theRoughCode** [comment]
This has been fixed.  Thanks!  :)
