### ISSUE TITLE
Funny oldPassword hehe

### ISSUE THREAD

**Issue by MichLiang** [theRoughCode/WatsMyMajor#85]
The words appear on the little input area for passwords, it's on the profile page

<img width="524" alt="screen shot 2018-10-04 at 12 42 57 am" src="https://user-images.githubusercontent.com/37000837/46425619-bada5180-c76e-11e8-8ec2-137ce973b443.png">

**Comment by keithcheung** [comment]
@theRoughCode !

**Comment by keithcheung** [comment]
https://github.com/theRoughCode/WatsMyMajor/pull/89

**Comment by theRoughCode** [comment]
Awesome thanks!
