### ISSUE TITLE
Open courses in new tab in MyCourses

### ISSUE THREAD

**Issue by theRoughCode** [theRoughCode/WatsMyMajor#86]
**Describe the bug**
We want to be able to open the courses in a new tab when clicking on a course card in "My Courses".

**To Reproduce**
1. Go to 'watsmymajor.com/my-courses'
2. Click on any course

**Expected behavior**
1. Opens in new tab
2. (Optional, but would be really good) Opens in current tab but acts as a link with right click to open in new tab

**Additional context**
Look into react-router-dom

**Comment by keithcheung** [comment]
I'm going to be taking this course as well
