### ISSUE TITLE
Failed to create account

### ISSUE THREAD

**Issue by TheVirtualMachine** [theRoughCode/WatsMyMajor#92]
**Describe the bug**
I tried to create an account both with my @edu.uwaterloo.ca email and the "friendly" @uwaterloo.ca email. With both emails, I get the error "Failed to create account. Please contact an administrator." when trying to log in after verifying my email address.

**To Reproduce**
1. Sign up for an account
2. Click on link in verification email
3. Try to login

**Expected behavior**
Logging in succeeds after verifying my email

**Desktop (please complete the following information):**
 - OS: Fedora Linux
 - Browser Firefox

**Comment by theRoughCode** [comment]
@TheVirtualMachine Hey, thanks for reporting the issue!  What's your username?

**Comment by TheVirtualMachine** [comment]
I tried PMathCODoubleMajor and when that didn't work I tried PMathCODoubleMajor2.

**Comment by theRoughCode** [comment]
It looks like you're already verified for both accounts.  Can you try logging in again?  I'll check the logs on my end.

**Comment by TheVirtualMachine** [comment]
I think my browser got confused during registration and mixed up the username with the email. Thanks!
